name: Ansible Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Lint Ansible Playbooks
      uses: ansible/ansible-lint-action@v6
      with:
        targets: "room-assistant.yml"
